-- ============================================================
-- Demeter · esquema de Supabase tal como está en producción
-- Sacado del proyecto el 28-sep-2026 (estructura, sin datos).
-- NO volver a correr en producción: es el punto de partida y sirve
-- para recrear la base desde cero si hiciera falta.
-- Los cambios nuevos van en archivos numerados (002_, 003_, …).
-- ============================================================

-- ---------- Mise and Please ----------
create table public.mise_items (
  id bigint generated by default as identity not null,
  cat text not null,
  ctx text,
  txt text not null,
  "position" integer not null default 0,
  constraint mise_items_pkey primary key (id)
);

create table public.mise_lista (
  id bigint generated by default as identity not null,
  cat text not null,
  ctx text,
  txt text not null,
  done boolean not null default false,
  "position" integer not null default 0,
  created_at timestamp with time zone not null default now(),
  comment text,
  constraint mise_lista_pkey primary key (id)
);

-- ---------- Protocolos ----------
-- protocolos_items: ítems editables de cada checklist (proto = 'apertura' | 'cierre').
-- protocolos_dia: una fila por protocolo y día con el estado de la checklist
--   (items en jsonb), las notas del turno y si se marcó terminado. El historial sale de acá.
create table public.protocolos_items (
  id bigint generated by default as identity not null,
  proto text not null,
  txt text not null,
  "position" integer not null default 0,
  constraint protocolos_items_pkey primary key (id)
);

create table public.protocolos_dia (
  id bigint generated by default as identity not null,
  proto text not null,
  dia date not null,
  items jsonb not null default '[]'::jsonb,
  notas text,
  terminado boolean not null default false,
  updated_at timestamp with time zone not null default now(),
  constraint protocolos_dia_pkey primary key (id),
  constraint protocolos_dia_proto_dia_key unique (proto, dia)
);

-- ---------- Stock y Pedidos ----------
create table public.stock_items (
  id bigint generated by default as identity not null,
  categoria text,
  proveedor text,
  item text not null,
  paquete text,
  por_paquete numeric not null default 0,
  cantidad_minima numeric not null default 0,
  ideal numeric not null default 0,
  "position" integer not null default 0,
  created_at timestamp with time zone not null default now(),
  constraint stock_items_pkey primary key (id)
);

create table public.stock_registros (
  id bigint generated by default as identity not null,
  fecha date not null default ((now() at time zone 'America/Montevideo'::text))::date,
  created_at timestamp with time zone not null default now(),
  constraint stock_registros_pkey primary key (id)
);

create table public.stock_registro_items (
  id bigint generated by default as identity not null,
  registro_id bigint not null,
  categoria text,
  proveedor text,
  item text not null,
  paquete text,
  por_paquete numeric not null default 0,
  cantidad_minima numeric not null default 0,
  ideal numeric not null default 0,
  cantidad_actual numeric not null default 0,
  "position" integer not null default 0,
  constraint stock_registro_items_pkey primary key (id),
  constraint stock_registro_items_registro_id_fkey foreign key (registro_id)
    references public.stock_registros(id) on delete cascade
);

-- ---------- Tabla de prueba (ninguna app la usa) ----------
create table public.notas_prueba (
  id bigint generated by default as identity not null,
  texto text not null,
  hecho boolean default false,
  creado_en timestamp with time zone default now(),
  constraint notas_prueba_pkey primary key (id)
);

-- ---------- Seguridad por filas (RLS) ----------
-- OJO: hoy todas las reglas están abiertas (using (true)): cualquiera con la
-- URL y la anon key puede leer, cambiar o borrar. Se cierra en una migración aparte.
alter table public.mise_items           enable row level security;
alter table public.mise_lista           enable row level security;
alter table public.protocolos_items     enable row level security;
alter table public.protocolos_dia       enable row level security;
alter table public.stock_items          enable row level security;
alter table public.stock_registros      enable row level security;
alter table public.stock_registro_items enable row level security;
alter table public.notas_prueba         enable row level security;

create policy "acceso publico mise_items" on public.mise_items
  as permissive for all to anon using (true) with check (true);
create policy "acceso publico mise_lista" on public.mise_lista
  as permissive for all to anon using (true) with check (true);
create policy "acceso publico protocolos_items" on public.protocolos_items
  as permissive for all to anon using (true) with check (true);
create policy pub_dia on public.protocolos_dia
  as permissive for all to anon using (true) with check (true);
create policy "acceso publico stock_items" on public.stock_items
  as permissive for all to anon using (true) with check (true);
create policy "acceso publico stock_registros" on public.stock_registros
  as permissive for all to anon using (true) with check (true);
create policy "acceso publico stock_registro_items" on public.stock_registro_items
  as permissive for all to anon using (true) with check (true);
create policy "acceso publico prueba" on public.notas_prueba
  as permissive for all to public using (true) with check (true);

-- ---------- Tiempo real ----------
alter publication supabase_realtime add table public.mise_lista;
alter publication supabase_realtime add table public.protocolos_dia;
