-- ============================================================
-- 002 · Crear mise_tareas (tareas del día de Mise and Please)
-- Mise la usa en ⚙ → "Tareas del día" pero no existía en la base,
-- así que guardar esas tareas fallaba. Columnas según el código:
-- cat, txt, dia ("Todos los días" | "Lunes" … "Domingo"), position.
-- Mismo nivel de acceso que el resto de las tablas por ahora
-- (se cierra junto con las demás cuando se haga el login).
-- Correr UNA vez en Supabase → SQL Editor.
-- ============================================================
create table public.mise_tareas (
  id bigint generated by default as identity not null,
  cat text,
  txt text not null,
  dia text not null default 'Todos los días',
  "position" integer not null default 0,
  constraint mise_tareas_pkey primary key (id)
);

alter table public.mise_tareas enable row level security;

create policy "acceso publico mise_tareas" on public.mise_tareas
  as permissive for all to anon using (true) with check (true);
