-- ============================================================
-- Demeter · FOTO COMPLETA de la base de Supabase (estructura, sin datos)
-- Sacada del proyecto el 28-sep-2026, con las migraciones 001 a 006 aplicadas.
--
-- Para saber cómo está la base HOY, mirar este archivo (no hace falta leer
-- las migraciones). Las migraciones numeradas (00X_…) son el historial de
-- cambios; después de correr una nueva, actualizar esta foto.
-- NO correr este archivo en producción: sirve para consultar o para
-- recrear la base desde cero en un proyecto vacío.
--
-- Ojo: casi todos los id son "generated ALWAYS as identity": al insertar,
-- no mandar id (da error 428C9). mise_tareas es "by default".
-- ============================================================


-- ============ Protocolos ============

-- Ítems editables de cada checklist (proto = 'apertura' | 'cierre').
create table public.protocolos_items (
  id bigint generated always as identity not null,
  proto text not null,
  txt text not null,
  "position" integer not null default 0,
  constraint protocolos_items_pkey primary key (id)
);

-- Una fila por protocolo y día: ítems marcados (jsonb [{txt, done}]), notas del
-- turno, si se terminó y a qué hora. El Registro de Protocolos y el panel salen de acá.
create table public.protocolos_dia (
  id bigint generated always as identity not null,
  proto text not null,
  dia date not null,
  items jsonb not null default '[]'::jsonb,
  notas text,
  terminado boolean not null default false,
  updated_at timestamp with time zone not null default now(),
  terminado_at timestamp with time zone,
  constraint protocolos_dia_pkey primary key (id),
  constraint protocolos_dia_proto_dia_key unique (proto, dia)
);

-- Horario de cada protocolo (desde / hasta; null = sin límite).
create table public.protocolos_config (
  proto text not null,
  hasta time without time zone,
  updated_at timestamp with time zone not null default now(),
  desde time without time zone,
  constraint protocolos_config_pkey primary key (proto)
);


-- ============ Mise and Please ============

-- Ítems del swipe (editables en ⚙).
create table public.mise_items (
  id bigint generated always as identity not null,
  cat text not null,
  ctx text,
  txt text not null,
  "position" integer not null default 0,
  constraint mise_items_pkey primary key (id)
);

-- Lista de producción abierta, compartida en vivo. Se borra con "Volver a empezar".
-- tipo: 'produccion' | 'tarea' (null = se deduce comparando con mise_tareas).
create table public.mise_lista (
  id bigint generated always as identity not null,
  cat text not null,
  ctx text,
  txt text not null,
  done boolean not null default false,
  "position" integer not null default 0,
  created_at timestamp with time zone not null default now(),
  comment text,
  tipo text,
  constraint mise_lista_pkey primary key (id)
);

-- Tareas del día (limpieza, mantenimiento…), editables en ⚙ → Tareas del día.
-- dia: 'Todos los días' | 'Lunes' … 'Domingo'.
create table public.mise_tareas (
  id bigint generated by default as identity not null,
  cat text,
  txt text not null,
  dia text not null default 'Todos los días'::text,
  "position" integer not null default 0,
  constraint mise_tareas_pkey primary key (id)
);

-- Registro diario (lo llena solo el trigger de abajo; lo lee el panel).
create table public.mise_registros (
  fecha date not null,
  prod_total integer not null default 0,
  prod_hechas integer not null default 0,
  tareas_total integer not null default 0,
  tareas_hechas integer not null default 0,
  items jsonb not null default '[]'::jsonb,
  updated_at timestamp with time zone not null default now(),
  constraint mise_registros_pkey primary key (fecha)
);


-- ============ Stock y Pedidos ============

create table public.stock_items (
  id bigint generated always as identity not null,
  categoria text,
  proveedor text,
  item text not null,
  paquete text,
  por_paquete numeric not null default 0,
  cantidad_minima numeric not null default 0,
  ideal numeric not null default 0,
  "position" integer not null default 0,
  created_at timestamp with time zone not null default now(),
  constraint stock_items_pkey primary key (id)
);

-- Un registro (conteo) por día.
create table public.stock_registros (
  id bigint generated always as identity not null,
  fecha date not null default ((now() at time zone 'America/Montevideo'::text))::date,
  created_at timestamp with time zone not null default now(),
  constraint stock_registros_pkey primary key (id),
  constraint stock_registros_fecha_key unique (fecha)
);

-- Foto de cada ítem en ese conteo. contado = false → "sin anotar" (no se pide).
create table public.stock_registro_items (
  id bigint generated always as identity not null,
  registro_id bigint not null,
  categoria text,
  proveedor text,
  item text not null,
  paquete text,
  por_paquete numeric not null default 0,
  cantidad_minima numeric not null default 0,
  ideal numeric not null default 0,
  cantidad_actual numeric not null default 0,
  "position" integer not null default 0,
  contado boolean not null default false,
  constraint stock_registro_items_pkey primary key (id),
  constraint stock_registro_items_registro_id_fkey foreign key (registro_id)
    references public.stock_registros(id) on delete cascade
);


-- ============ Tabla de prueba (ninguna app la usa; se puede borrar) ============

create table public.notas_prueba (
  id bigint generated always as identity not null,
  texto text not null,
  hecho boolean default false,
  creado_en timestamp with time zone default now(),
  constraint notas_prueba_pkey primary key (id)
);


-- ============ Seguridad por filas (RLS) ============
-- OJO: hoy todas las reglas están abiertas (using (true)): cualquiera con la URL
-- y la anon key puede leer, cambiar o borrar. Se cierra cuando se haga el login.

alter table public.protocolos_items     enable row level security;
alter table public.protocolos_dia       enable row level security;
alter table public.protocolos_config    enable row level security;
alter table public.mise_items           enable row level security;
alter table public.mise_lista           enable row level security;
alter table public.mise_tareas          enable row level security;
alter table public.mise_registros       enable row level security;
alter table public.stock_items          enable row level security;
alter table public.stock_registros      enable row level security;
alter table public.stock_registro_items enable row level security;
alter table public.notas_prueba         enable row level security;

create policy "acceso publico protocolos_items" on public.protocolos_items
  as permissive for all to anon using (true) with check (true);
create policy pub_dia on public.protocolos_dia
  as permissive for all to anon using (true) with check (true);
create policy "acceso publico protocolos_config" on public.protocolos_config
  as permissive for all to anon using (true) with check (true);
create policy "acceso publico mise_items" on public.mise_items
  as permissive for all to anon using (true) with check (true);
create policy "acceso publico mise_lista" on public.mise_lista
  as permissive for all to anon using (true) with check (true);
create policy "acceso publico mise_tareas" on public.mise_tareas
  as permissive for all to anon using (true) with check (true);
create policy "acceso publico mise_registros" on public.mise_registros
  as permissive for all to anon using (true) with check (true);
create policy "acceso publico stock_items" on public.stock_items
  as permissive for all to anon using (true) with check (true);
create policy "acceso publico stock_registros" on public.stock_registros
  as permissive for all to anon using (true) with check (true);
create policy "acceso publico stock_registro_items" on public.stock_registro_items
  as permissive for all to anon using (true) with check (true);
create policy "acceso publico prueba" on public.notas_prueba
  as permissive for all to public using (true) with check (true);


-- ============ Tiempo real ============

alter publication supabase_realtime add table public.mise_lista;
alter publication supabase_realtime add table public.protocolos_dia;


-- ============ Registro diario de Mise (función + trigger) ============

create or replace function public.mise_registrar_dia()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  f date := (coalesce(new.created_at, now()) at time zone 'America/Montevideo')::date;
begin
  with filas as (
    select l.*,
           coalesce(l.tipo,
             case when exists (select 1 from mise_tareas t where t.txt = l.txt)
                  then 'tarea' else 'produccion' end) as tipo_ok
    from mise_lista l
    where (l.created_at at time zone 'America/Montevideo')::date = f
  )
  insert into mise_registros (fecha, prod_total, prod_hechas, tareas_total, tareas_hechas, items, updated_at)
  select f,
         count(*) filter (where tipo_ok = 'produccion'),
         count(*) filter (where tipo_ok = 'produccion' and done),
         count(*) filter (where tipo_ok = 'tarea'),
         count(*) filter (where tipo_ok = 'tarea' and done),
         coalesce(jsonb_agg(jsonb_build_object(
           'cat', cat, 'txt', txt, 'done', done, 'tipo', tipo_ok, 'comment', comment)
           order by "position"), '[]'::jsonb),
         now()
  from filas
  having count(*) > 0
  on conflict (fecha) do update set
    prod_total    = excluded.prod_total,
    prod_hechas   = excluded.prod_hechas,
    tareas_total  = excluded.tareas_total,
    tareas_hechas = excluded.tareas_hechas,
    items         = excluded.items,
    updated_at    = excluded.updated_at;
  return null;
end;
$function$;

create trigger mise_lista_registrar
  after insert or update on public.mise_lista
  for each row execute function public.mise_registrar_dia();
